name: Ionic Build Android
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: nrwl/nx-set-shas@v3
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:all:android
      - name: Run Lint
        run: npm run lint:all:apps
